#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

###################################################################################################
# newhire service
###################################################################################################
{{- $appname := include "newhire.name" . -}}
{{- $chart := include "newhire.chart" . -}}
{{- $instancename := .Release.Name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $appname }}
  labels:
    app.kubernetes.io/name: {{ $appname }}
    app.kubernetes.io/instance: {{ $instancename }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: backend
    helm.sh/chart: {{ $chart }}
spec:
  ports:
  - name: http
    port: 8806
    targetPort: 8806
  selector:
    app.kubernetes.io/name: {{ $appname }}
    app.kubernetes.io/instance: {{ $instancename }}
