# Uat values for newhire.
nameOverride: newhire
exports:
  data:
    enable_cors: true
    hosts: https://portaluat.mybbsi.com
    ssl_redirect: true
    replicaCount: 1
    image:
      pullPolicy: Always
    telemetry:
      level: "Information"
    reason: "new uat deploy"
    current: true
    ingress:
      class: "nginx-uat"
    resources:
      requests:
        cpu: 500m
        memory: 1024Mi
      limits:
        cpu: 1000m
        memory: 3096Mi
    env:
      user_management: http://usermgmt.backend-uat.svc.cluster.local:8801
      employee_management: http://empmgmt.backend-uat.svc.cluster.local:8803
      notification_management: http://notifymgmt.backend-uat.svc.cluster.local:8807
      integration_management: http://intmgmt.backend-uat.svc.cluster.local:8810
      reference_mgmt: http://refmgmt.backend-uat.svc.cluster.local:8804
      employee_newhire: http://newhire.backend-uat.svc.cluster.local:8806
      dashboard: http://dashboard.backend-uat.svc.cluster.local:8808
      client: http://client.backend-uat.svc.cluster.local:8802
      reportsmgmt: http://reportsmgmt.backend-uat.svc.cluster.local:8812
      tokenmgmt: http://tokenmgmt.backend-uat.svc.cluster.local:8813
      confserver: http://confserver.backend-uat.svc.cluster.local:4000
      rabbitmqhost: rabbitmq.rabbitmq-uat.svc.cluster.local
      rabbitmqport: 5672