dependencies:
  - name: newhire-dev
    repository: "file://envs/newhire-dev"
    version: ">= 0.0.1"
    tags:
      - dev
    import-values:
      - data

  - name: newhire-perf
    repository: "file://envs/newhire-perf"
    version: ">= 0.0.1"
    tags:
      - perf
    import-values:
      - data

  - name: newhire-qa
    repository: "file://envs/newhire-qa"
    version: ">= 0.0.1"
    tags:
      - qa
    import-values:
      - data

  - name: newhire-uat
    repository: "file://envs/newhire-uat"
    version: ">= 0.0.1"
    tags:
      - uat
    import-values:
      - data
  
  - name: newhire-trng
    repository: "file://envs/newhire-trng"
    version: ">= 0.0.1"
    tags:
      - trng
    import-values:
      - data

  - name: newhire-altdev
    repository: "file://envs/newhire-altdev"
    version: ">= 0.0.1"
    tags:
      - altdev
    import-values:
      - data    

  - name: newhire-prod
    repository: "file://envs/newhire-prod"
    version: ">= 0.0.1"
    tags:
      - prod
    import-values:
      - data    

  - name: newhire-altqa
    repository: "file://envs/newhire-altqa"
    version: ">= 0.0.1"
    tags:
      - altqa
    import-values:
      - data      

  - name: newhire-prdspt
    repository: "file://envs/newhire-prdspt"
    version: ">= 0.0.1"
    tags:
      - prdspt
    import-values:
      - data  