# Default values for authymfa.
nameOverride: newhire
replicaCount: 1
dockerregistry:
image:
  repository:
  tag:
  pullPolicy: Always
readinessProbe:
  httpGet:
    path: /healthz
    port: 8806
  initialDelaySeconds: 40
  periodSeconds: 15
  timeoutSeconds: 2
  failureThreshold: 5
livenessProbe:
  httpGet:
    path: /healthz
    port: 8806
  initialDelaySeconds: 50
  periodSeconds: 15
telemetry:
  level: "Error"
reason: unknown
tags:
  dev: false
  perf: false
  qa: false
  uat: false
  trng: false
  altdev: false
  altqa: false
  prod: false
current: false
autoscaling:
  enabled: false
  maxReplicas:
  minReplicas:
  targetCPUUtilizationPercentage:
env:
  user_management:
  employee_management:
  notification_management:
  integration_management:
  reference_mgmt:
  employee_newhire:
  # reporting:
  dashboard:
  # datamigrate:
  client:
  # confclient:
  # confemp:
  reportsmgmt:
  confserver:
  audit_enable:
  tokenmgmt:
  datadog_env:
  jobmgmt: