# prdspt values for newhire.
nameOverride: newhire
exports:
  data:
    enable_cors: true
    hosts: https://portalprdspt.mybbsi.com 
    ssl_redirect: true
    replicaCount: 1
    image:
      pullPolicy: Always
    telemetry:
      level: "Information"
    reason: "new prdspt deploy"
    current: true
    ingress:
      class: "nginx-prdspt"
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    autoscaling:
      enabled: false
      maxReplicas: 4
      minReplicas: 3
      targetCPUUtilizationPercentage: 75
    env:
      user_management: http://usermgmt.backend-prdspt.svc.cluster.local:8801
      employee_management: http://empmgmt.backend-prdspt.svc.cluster.local:8803
      notification_management: http://notifymgmt.backend-prdspt.svc.cluster.local:8807
      integration_management: http://intmgmt.backend-prdspt.svc.cluster.local:8810
      reference_mgmt: http://refmgmt.backend-prdspt.svc.cluster.local:8804
      employee_newhire: http://newhire.backend-prdspt.svc.cluster.local:8806
      dashboard: http://dashboard.backend-prdspt.svc.cluster.local:8808
      client: http://client.backend-prdspt.svc.cluster.local:8802
      reportsmgmt: http://reportsmgmt.backend-prdspt.svc.cluster.local:8812
      tokenmgmt: http://tokenmgmt.backend-prdspt.svc.cluster.local:8813
      confserver: http://confserver.backend-prdspt.svc.cluster.local:4000
      rabbitmqhost: rabbitmq.rabbitmq-prdspt.svc.cluster.local
      rabbitmqport: 5672
      audit_enable: true
      datadog_env: prodsup
