# QA values for usermgmt.
nameOverride: usermgmt
exports:
  data:
    enable_cors: true
    hosts: https://portalqa.mybbsi.com
    ssl_redirect: true  
    replicaCount: 1
    image:
      pullPolicy: Always
    telemetry:
      level: "Information"
    reason: "new qa deploy"
    current: true
    ingress:
      class: "nginx-qa"
    resources:
      requests:
        cpu: 500M
        memory: 1.5Gi
      limits:
        cpu: 1000M
        memory: 3Gi
    env:
      user_management: http://usermgmt.backend-qa.svc.cluster.local:8801
      employee_management: http://empmgmt.backend-qa.svc.cluster.local:8803
      notification_management: http://notifymgmt.backend-qa.svc.cluster.local:8807
      integration_management: http://intmgmt.backend-qa.svc.cluster.local:8810
      reference_mgmt: http://refmgmt.backend-qa.svc.cluster.local:8804
      employee_newhire: http://newhire.backend-qa.svc.cluster.local:8806
      dashboard: http://dashboard.backend-qa.svc.cluster.local:8808
      client: http://client.backend-qa.svc.cluster.local:8802
      reportsmgmt: http://reportsmgmt.backend-qa.svc.cluster.local:8812
      jobmgmt: http://jobmgmt.backend-qa.svc.cluster.local:8814
      tokenmgmt: http://tokenmgmt.backend-qa.svc.cluster.local:8813
      confserver: http://confserver.backend-qa.svc.cluster.local:4000
      rabbitmqhost: rabbitmq.rabbitmq-qa.svc.cluster.local
      rabbitmqport: 5672
      audit_enable: true